"""Create event_exceptions table

Revision ID: 3c2bc8802b38
Revises: 83ea9fe5da9b
Create Date: 2025-07-15 14:25:48.806947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2bc8802b38'
down_revision = '83ea9fe5da9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_event_id', sa.Integer(), nullable=True),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_exceptions')
    # ### end Alembic commands ###
